In [27]:
import numpy as np
import control as ct

In [28]:
g = 9.81
kt = 0.1
kr = 0.1
m = 0.65
Ix = 7.5e-3
Iy = Ix
Iz = 1.3e-2
A = np.array([
    [0,0,0,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,-1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,-g,0,0,0,0],
    [0,0,0,0,0,0,g,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
])

In [29]:
A.shape

(12, 12)

In [30]:
B = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [-1/m,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,1/Ix,0,0],
    [0,0,1/Iy,0],
    [0,0,0,1/Iz],
])

In [31]:
eignenvalues, _ = np.linalg.eig(A)
np.real(eignenvalues)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.linalg.matrix_rank(ct.ctrb(A,B,12))

12

In [33]:
np.linalg.matrix_rank(ct.obsv(A,np.array([
    [1,0,0,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,1,0,0,0,0,0,0],
])))

10

In [4]:
dt = 0.1
time = np.arange(0,20,dt)
np.sin(2*time)

array([ 0.        ,  0.19866933,  0.38941834,  0.56464247,  0.71735609,
        0.84147098,  0.93203909,  0.98544973,  0.9995736 ,  0.97384763,
        0.90929743,  0.8084964 ,  0.67546318,  0.51550137,  0.33498815,
        0.14112001, -0.05837414, -0.2555411 , -0.44252044, -0.61185789,
       -0.7568025 , -0.87157577, -0.95160207, -0.993691  , -0.99616461,
       -0.95892427, -0.88345466, -0.77276449, -0.63126664, -0.46460218,
       -0.2794155 , -0.0830894 ,  0.1165492 ,  0.31154136,  0.49411335,
        0.6569866 ,  0.79366786,  0.8987081 ,  0.96791967,  0.99854335,
        0.98935825,  0.94073056,  0.85459891,  0.7343971 ,  0.58491719,
        0.41211849,  0.22288991,  0.02477543, -0.17432678, -0.36647913,
       -0.54402111, -0.69987469, -0.82782647, -0.92277542, -0.98093623,
       -0.99999021, -0.97917773, -0.91932853, -0.82282859, -0.69352508,
       -0.53657292, -0.35822928, -0.16560418,  0.03362305,  0.23150983,
        0.42016704,  0.59207351,  0.74037589,  0.85916181,  0.94

In [ ]:
from trajectory import Trajectory

Trajectory.sine_wave(0.1,20,5,0.5)

(200,)

In [3]:
import control as ct
import numpy as np

In [5]:
g = 9.81
m = 0.547
Ix = 3.3e-3
Iy = 3.3e-3
Iz = 5.8e-3

In [6]:
A = np.array([
    [0,0,0,0,0,0,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,0,0,0],
    [0,0,0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,g,0,0,0,0,0,0,0],
    [0,0,0,-g,0,0,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0],
])

In [7]:
B = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [1/m,0,0,0],
    [0,1/Ix,0,0],
    [0,0,1/Iy,0],
    [0,0,0,1/Iz],
])

In [20]:
sys = ct.ss(A,B,np.eye(12),np.zeros((12,4)))

In [27]:
sysd = sys.sample(0.1)

In [39]:
print(sysd.A)

[[ 1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  4.9050e-02  0.0000e+00
   1.0000e-01  0.0000e+00  0.0000e+00  0.0000e+00  1.6350e-03  0.0000e+00]
 [ 0.0000e+00  1.0000e+00  0.0000e+00 -4.9050e-02  1.6350e-03  0.0000e+00
   5.0000e-03  1.0000e-01  0.0000e+00 -1.6350e-03  4.0875e-05  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  1.0000e-01  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  1.0000e-01  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e-01  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e-01]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  9.8100e-01  0.0000e+00
   1.0000e+00  0.0000e+00  0.000

In [22]:
print(sysd.A)

[[ 1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  4.9050e-02  0.0000e+00
   1.0000e-01  0.0000e+00  0.0000e+00  0.0000e+00  1.6350e-03  0.0000e+00]
 [ 0.0000e+00  1.0000e+00  0.0000e+00 -4.9050e-02  1.6350e-03  0.0000e+00
   5.0000e-03  1.0000e-01  0.0000e+00 -1.6350e-03  4.0875e-05  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  1.0000e-01  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  1.0000e-01  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e-01  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e-01]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  9.8100e-01  0.0000e+00
   1.0000e+00  0.0000e+00  0.000

In [24]:
sysd.nstates

12

In [26]:
np.shape(sysd.A)

(12, 12)

In [40]:
x = np.array([0,0,0,0,0,0,0,0,0,0,0,0])

u = np.array([1,0,0,0])

In [53]:
x = sysd.A @ x + sysd.B @ u
type(x)

numpy.ndarray

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [60]:
arr.flatten('F')

array([1, 4, 2, 5, 3, 6])